set(freeImageSources
	${FREEIMAGE_DIR}/Source/FreeImage/BitmapAccess.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ColorLookup.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/FreeImage.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/FreeImageC.c
	${FREEIMAGE_DIR}/Source/FreeImage/FreeImageIO.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/GetType.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/MemoryIO.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PixelAccess.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/J2KHelper.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/MNGHelper.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Plugin.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginBMP.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginCUT.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginDDS.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginEXR.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginG3.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginGIF.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginHDR.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginICO.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginIFF.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginJ2K.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginJNG.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginJP2.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginJPEG.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginJXR.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginKOALA.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginMNG.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPCD.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPCX.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPFM.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPICT.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPNG.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPNM.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginPSD.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginRAS.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginRAW.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginSGI.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginTARGA.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginTIFF.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginWBMP.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginWebP.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginXBM.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PluginXPM.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/PSDParser.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/TIFFLogLuv.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion16_555.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion16_565.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion24.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion32.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion4.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Conversion8.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionFloat.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionRGB16.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionRGBA16.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionRGBAF.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionRGBF.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionType.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ConversionUINT16.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/Halftoning.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/tmoColorConvert.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/tmoDrago03.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/tmoFattal02.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/tmoReinhard05.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ToneMapping.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/LFPQuantizer.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/NNQuantizer.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/WuQuantizer.cpp
	${FREEIMAGE_DIR}/Source/DeprecationManager/Deprecated.cpp
	${FREEIMAGE_DIR}/Source/DeprecationManager/DeprecationMgr.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/CacheFile.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/MultiPage.cpp
	${FREEIMAGE_DIR}/Source/FreeImage/ZLibInterface.cpp
	${FREEIMAGE_DIR}/Source/Metadata/Exif.cpp
	${FREEIMAGE_DIR}/Source/Metadata/FIRational.cpp
	${FREEIMAGE_DIR}/Source/Metadata/FreeImageTag.cpp
	${FREEIMAGE_DIR}/Source/Metadata/IPTC.cpp
	${FREEIMAGE_DIR}/Source/Metadata/TagConversion.cpp
	${FREEIMAGE_DIR}/Source/Metadata/TagLib.cpp
	${FREEIMAGE_DIR}/Source/Metadata/XTIFF.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Background.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/BSplineRotate.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Channels.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/ClassicRotate.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Colors.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/CopyPaste.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Display.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Flip.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/JPEGTransform.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/MultigridPoissonSolver.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Rescale.cpp
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Resize.cpp
	${FREEIMAGE_DIR}/Source/LibJPEG/jaricom.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcapimin.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcapistd.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcarith.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jccoefct.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jccolor.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcdctmgr.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jchuff.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcinit.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcmainct.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcmarker.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcmaster.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcomapi.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcparam.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcprepct.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jcsample.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jctrans.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdapimin.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdapistd.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdarith.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdatadst.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdatasrc.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdcoefct.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdcolor.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jddctmgr.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdhuff.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdinput.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdmainct.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdmarker.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdmaster.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdmerge.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdpostct.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdsample.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jdtrans.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jerror.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jfdctflt.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jfdctfst.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jfdctint.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jidctflt.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jidctfst.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jidctint.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jmemmgr.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jmemnobs.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jquant1.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jquant2.c
	${FREEIMAGE_DIR}/Source/LibJPEG/jutils.c
	${FREEIMAGE_DIR}/Source/LibJPEG/transupp.c
	${FREEIMAGE_DIR}/Source/LibPNG/png.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngerror.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngget.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngmem.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngpread.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngread.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngrio.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngrtran.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngrutil.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngset.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngtrans.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngwio.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngwrite.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngwtran.c
	${FREEIMAGE_DIR}/Source/LibPNG/pngwutil.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_aux.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_close.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_codec.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_color.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_compress.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_dir.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_dirinfo.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_dirread.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_dirwrite.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_dumpmode.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_error.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_extension.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_fax3.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_fax3sm.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_flush.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_getimage.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_jpeg.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_luv.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_lzma.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_lzw.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_next.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_ojpeg.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_open.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_packbits.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_pixarlog.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_predict.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_print.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_read.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_strip.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_swab.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_thunder.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_tile.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_version.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_warning.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_write.c
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_zip.c
	${FREEIMAGE_DIR}/Source/ZLib/adler32.c
	${FREEIMAGE_DIR}/Source/ZLib/compress.c
	${FREEIMAGE_DIR}/Source/ZLib/crc32.c
	${FREEIMAGE_DIR}/Source/ZLib/deflate.c
	${FREEIMAGE_DIR}/Source/ZLib/gzclose.c
	${FREEIMAGE_DIR}/Source/ZLib/gzlib.c
	${FREEIMAGE_DIR}/Source/ZLib/gzread.c
	${FREEIMAGE_DIR}/Source/ZLib/gzwrite.c
	${FREEIMAGE_DIR}/Source/ZLib/infback.c
	${FREEIMAGE_DIR}/Source/ZLib/inffast.c
	${FREEIMAGE_DIR}/Source/ZLib/inflate.c
	${FREEIMAGE_DIR}/Source/ZLib/inftrees.c
	${FREEIMAGE_DIR}/Source/ZLib/trees.c
	${FREEIMAGE_DIR}/Source/ZLib/uncompr.c
	${FREEIMAGE_DIR}/Source/ZLib/zutil.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/bio.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/cio.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/dwt.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/event.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/function_list.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/image.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/invert.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/j2k.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/jp2.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/mct.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/mqc.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/openjpeg.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_clock.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/pi.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/raw.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/t1.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/t2.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/tcd.c
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/tgt.c
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/b44ExpLogTable.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfAcesFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfB44Compressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfBoxAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChannelList.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChannelListAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChromaticities.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChromaticitiesAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompositeDeepScanLine.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompressionAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfConvert.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCRgbaFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepCompositing.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepFrameBuffer.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepImageStateAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineInputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledInputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledOutputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledOutputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDoubleAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDwaCompressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfEnvmap.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfEnvmapAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFastHuf.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFloatAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFloatVectorAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFrameBuffer.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFramesPerSecond.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfGenericInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfGenericOutputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfHeader.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfHuf.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputPartData.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfIntAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfIO.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfKeyCode.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfKeyCodeAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfLineOrderAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfLut.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMatrixAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMisc.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMultiPartInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMultiPartOutputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMultiView.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOpaqueAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputPartData.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPartType.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPizCompressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPreviewImage.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPreviewImageAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPxr24Compressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRational.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRationalAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRgbaFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRgbaYca.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRle.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRleCompressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfScanLineInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStandardAttributes.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStdIO.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStringAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStringVectorAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfSystemSpecific.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTestFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfThreading.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTileDescriptionAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledInputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledInputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledMisc.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledOutputFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledOutputPart.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledRgbaFile.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTileOffsets.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTimeCode.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTimeCodeAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfVecAttribute.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfVersion.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfWav.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfZip.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfZipCompressor.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathBox.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathColorAlgo.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathFun.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathMatrixAlgo.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathRandom.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathShear.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathVec.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexBaseExc.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexThrowErrnoExc.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/half.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThread.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadMutex.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadPool.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadSemaphore.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IexMath/IexMathFloatExc.cpp
	${FREEIMAGE_DIR}/Source/OpenEXR/IexMath/IexMathFpu.cpp
	${FREEIMAGE_DIR}/Source/LibRawLite/internal/dcraw_common.cpp
	${FREEIMAGE_DIR}/Source/LibRawLite/internal/dcraw_fileio.cpp
	${FREEIMAGE_DIR}/Source/LibRawLite/internal/demosaic_packs.cpp
	${FREEIMAGE_DIR}/Source/LibRawLite/src/libraw_c_api.cpp
	${FREEIMAGE_DIR}/Source/LibRawLite/src/libraw_cxx.cpp
	${FREEIMAGE_DIR}/Source/LibRawLite/src/libraw_datastream.cpp
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.alpha.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.buffer.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.frame.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.idec.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.io.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.quant.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.tree.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.vp8.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.vp8l.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/dec.webp.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.alpha_processing.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.alpha_processing_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.argb.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.argb_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.cost.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.cost_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.cpu.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.dec.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.dec_clip_tables.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.dec_neon.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.dec_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.enc.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.enc_avx2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.enc_neon.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.enc_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.filters.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.filters_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.lossless.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.lossless_neon.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.lossless_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.rescaler.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.upsampling.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.upsampling_neon.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.upsampling_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.yuv.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.yuv_sse2.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.alpha.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.analysis.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.backward_references.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.config.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.cost.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.filter.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.frame.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.histogram.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.iterator.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.near_lossless.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.picture.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.picture_csp.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.picture_psnr.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.picture_rescale.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.picture_tools.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.quant.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.syntax.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.token.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.tree.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.vp8l.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/enc.webpenc.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.bit_reader.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.bit_writer.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.color_cache.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.filters.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.huffman.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.huffman_encode.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.quant_levels.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.quant_levels_dec.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.random.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.rescaler.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.thread.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.utils.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/mux/mux.anim_encode.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/mux/mux.muxedit.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/mux/mux.muxinternal.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/mux/mux.muxread.c
	${FREEIMAGE_DIR}/Source/LibWebP/src/demux/demux.demux.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/decode.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/JXRTranscode.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/postprocess.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/segdec.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/strdec.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/strdec_x86.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/strInvTransform.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/strPredQuantDec.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/encode.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/segenc.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/strenc.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/strenc_x86.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/strFwdTransform.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/strPredQuantEnc.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/adapthuff.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/image.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/strcodec.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/strPredQuant.c
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/strTransform.c
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib/JXRGlue.c
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib/JXRGlueJxr.c
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib/JXRGluePFC.c
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib/JXRMeta.c
	${FREEIMAGE_DIR}/Source/MapIntrospector.h
	${FREEIMAGE_DIR}/Source/CacheFile.h
	${FREEIMAGE_DIR}/Source/LibJPEG/cderror.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jmorecfg.h
	${FREEIMAGE_DIR}/Source/LibJPEG/transupp.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jpeglib.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jversion.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jinclude.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jerror.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jconfig.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jdct.h
	${FREEIMAGE_DIR}/Source/LibJPEG/cdjpeg.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jmemsys.h
	${FREEIMAGE_DIR}/Source/LibJPEG/jpegint.h
	${FREEIMAGE_DIR}/Source/Plugin.h
	${FREEIMAGE_DIR}/Source/Metadata/FreeImageTag.h
	${FREEIMAGE_DIR}/Source/Metadata/FIRational.h
	${FREEIMAGE_DIR}/Source/ToneMapping.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_config.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_fax3.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tiffvers.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tiffio.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tiff.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/uvcode.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_dir.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/t4.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tif_predict.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tiffiop.h
	${FREEIMAGE_DIR}/Source/LibTIFF4/tiffconf.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/alphai.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/vp8li.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/decode_vp8.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/webpi.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dec/vp8i.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/vp8enci.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/histogram.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/vp8li.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/backward_references.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/enc/cost.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/huffman_encode.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/rescaler.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/bit_writer.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/huffman.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/quant_levels.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/thread.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/filters.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/random.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/quant_levels_dec.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/bit_reader_inl.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/color_cache.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/bit_reader.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/endian_inl.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/utils/utils.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/mux/muxi.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/mux.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/types.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/format_constants.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/demux.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/encode.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/decode.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/webp/mux_types.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/yuv.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/yuv_tables_sse2.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/neon.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/mips_macro.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/dsp.h
	${FREEIMAGE_DIR}/Source/LibWebP/src/dsp/lossless.h
	${FREEIMAGE_DIR}/Source/FreeImageIO.h
	${FREEIMAGE_DIR}/Source/FreeImage.h
	${FREEIMAGE_DIR}/Source/FreeImage/PSDParser.h
	${FREEIMAGE_DIR}/Source/FreeImage/J2KHelper.h
	${FREEIMAGE_DIR}/Source/ZLib/trees.h
	${FREEIMAGE_DIR}/Source/ZLib/inffixed.h
	${FREEIMAGE_DIR}/Source/ZLib/inflate.h
	${FREEIMAGE_DIR}/Source/ZLib/zlib.h
	${FREEIMAGE_DIR}/Source/ZLib/zconf.h
	${FREEIMAGE_DIR}/Source/ZLib/inftrees.h
	${FREEIMAGE_DIR}/Source/ZLib/zutil.h
	${FREEIMAGE_DIR}/Source/ZLib/inffast.h
	${FREEIMAGE_DIR}/Source/ZLib/crc32.h
	${FREEIMAGE_DIR}/Source/ZLib/gzguts.h
	${FREEIMAGE_DIR}/Source/ZLib/deflate.h
	${FREEIMAGE_DIR}/Source/Quantizers.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/cio.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/mqc.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/cidx_manager.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/function_list.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/indexbox_manager.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_config.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_clock.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/event.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_codec.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/pi.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/dwt.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/tgt.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/invert.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_malloc.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/raw.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/jp2.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/bio.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/t2.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/mct.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/t1.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/t1_luts.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/j2k.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_stdint.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_config_private.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_includes.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_intmath.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/image.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/opj_inttypes.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/openjpeg.h
	${FREEIMAGE_DIR}/Source/LibOpenJPEG/tcd.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw_version.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw_const.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw_types.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw_alloc.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw_datastream.h
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw/libraw_internal.h
	${FREEIMAGE_DIR}/Source/LibRawLite/internal/var_defines.h
	${FREEIMAGE_DIR}/Source/LibRawLite/internal/defines.h
	${FREEIMAGE_DIR}/Source/LibRawLite/internal/libraw_internal_funcs.h
	${FREEIMAGE_DIR}/Source/LibPNG/png.h
	${FREEIMAGE_DIR}/Source/LibPNG/pngdebug.h
	${FREEIMAGE_DIR}/Source/LibPNG/pnginfo.h
	${FREEIMAGE_DIR}/Source/LibPNG/pnglibconf.h
	${FREEIMAGE_DIR}/Source/LibPNG/pngstruct.h
	${FREEIMAGE_DIR}/Source/LibPNG/pngpriv.h
	${FREEIMAGE_DIR}/Source/LibPNG/pngconf.h
	${FREEIMAGE_DIR}/Source/LibJXR/common/include/wmspecstrings_strict.h
	${FREEIMAGE_DIR}/Source/LibJXR/common/include/wmspecstring.h
	${FREEIMAGE_DIR}/Source/LibJXR/common/include/guiddef.h
	${FREEIMAGE_DIR}/Source/LibJXR/common/include/wmsal.h
	${FREEIMAGE_DIR}/Source/LibJXR/common/include/wmspecstrings_undef.h
	${FREEIMAGE_DIR}/Source/LibJXR/common/include/wmspecstrings_adt.h
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib/JXRGlue.h
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib/JXRMeta.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/xplatform_image.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/strTransform.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/windowsmediaphoto.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/strcodec.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/ansi.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/perfTimer.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys/common.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/decode/decode.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/x86/x86.h
	${FREEIMAGE_DIR}/Source/LibJXR/image/encode/encode.h
	${FREEIMAGE_DIR}/Source/Utilities.h
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Resize.h
	${FREEIMAGE_DIR}/Source/FreeImageToolkit/Filters.h
	${FREEIMAGE_DIR}/Source/OpenEXR/OpenEXRConfig.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IexMath/IexMathFloatExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IexMath/IexMathFpu.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IexMath/IexMathIeeeExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThread.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadMutex.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadForward.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadExport.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadSemaphore.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadPool.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread/IlmThreadNamespace.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexErrnoExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexMacros.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexForward.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexExport.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexThrowErrnoExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexNamespace.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexMathExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/IexBaseExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex/Iex.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathColorAlgo.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathNamespace.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathVec.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathGL.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathSphere.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathEuler.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathLimits.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathQuat.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathRoots.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathFun.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathExport.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathShear.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathPlane.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathForward.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathHalfLimits.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathFrustumTest.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathMatrixAlgo.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathVecAlgo.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathInterval.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathBox.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathFrame.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathColor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathMath.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathLine.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathBoxAlgo.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathFrustum.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathExc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathLineAlgo.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathRandom.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathInt64.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathGLU.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathPlatform.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath/ImathMatrix.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfIO.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStdIO.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPreviewImage.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDwaCompressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChannelList.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInt64.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfGenericOutputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfHuf.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOptimizedPixelReading.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/b44ExpLogTable.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMultiPartOutputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTileDescriptionAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFastHuf.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/dwaLookups.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompositeDeepScanLine.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepFrameBuffer.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputPartData.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfAcesFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRgbaYca.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfThreading.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfWav.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChromaticitiesAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDwaCompressorSimd.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfNamespace.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMatrixAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTimeCodeAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineInputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFloatAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPxr24Compressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCRgbaFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledInputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRationalAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTileOffsets.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputStreamMutex.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfIntAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledOutputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPartType.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStringAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledOutputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRleCompressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChromaticities.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTestFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfInputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfXdr.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfExport.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRgba.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfLineOrder.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompression.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledMisc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFramesPerSecond.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfZipCompressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfKeyCodeAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFloatVectorAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMultiPartInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledOutputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRational.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepImageStateAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfChannelListAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepCompositing.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputPartData.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledInputPart.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPreviewImageAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfFrameBuffer.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepImageState.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOpaqueAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfEnvmapAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPizCompressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStringVectorAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMultiView.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfAutoArray.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfLut.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledOutputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfBoxAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCheckedArithmetic.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfB44Compressor.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfSystemSpecific.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRgbaFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTimeCode.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfVecAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDeepTiledInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfZip.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfConvert.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfMisc.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfHeader.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfForward.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPartHelper.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfKeyCode.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfVersion.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfStandardAttributes.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfPixelType.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfName.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfSimd.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfArray.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfOutputStreamMutex.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTiledRgbaFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfRle.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfScanLineInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfDoubleAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfGenericInputFile.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfEnvmap.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfLineOrderAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfTileDescription.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf/ImfCompressionAttribute.h
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmBaseConfig.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/halfFunction.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/halfExport.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/half.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/eLut.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/halfLimits.h
	${FREEIMAGE_DIR}/Source/OpenEXR/Half/toFloat.h
	${FREEIMAGE_DIR}/Source/DeprecationManager/DeprecationMgr.h
)

set(FreeImage_INCLUDE_DIRS
	${FREEIMAGE_DIR}/Source
	${FREEIMAGE_DIR}/Source/Metadata
	${FREEIMAGE_DIR}/Source/FreeImageToolkit
	${FREEIMAGE_DIR}/Source/LibJPEG
	${FREEIMAGE_DIR}/Source/LibPNG
	${FREEIMAGE_DIR}/Source/LibTIFF4
	${FREEIMAGE_DIR}/Source/ZLib
	${FREEIMAGE_DIR}/Source/LibOpenJPEG
	${FREEIMAGE_DIR}/Source/OpenEXR
	${FREEIMAGE_DIR}/Source/OpenEXR/Half
	${FREEIMAGE_DIR}/Source/OpenEXR/Iex
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmImf
	${FREEIMAGE_DIR}/Source/OpenEXR/IlmThread
	${FREEIMAGE_DIR}/Source/OpenEXR/Imath
	${FREEIMAGE_DIR}/Source/OpenEXR/IexMath
	${FREEIMAGE_DIR}/Source/LibRawLite
	${FREEIMAGE_DIR}/Source/LibRawLite/dcraw
	${FREEIMAGE_DIR}/Source/LibRawLite/internal
	${FREEIMAGE_DIR}/Source/LibRawLite/libraw
	${FREEIMAGE_DIR}/Source/LibRawLite/src
	${FREEIMAGE_DIR}/Source/LibWebP
	${FREEIMAGE_DIR}/Source/LibJXR
	${FREEIMAGE_DIR}/Source/LibJXR/common/include
	${FREEIMAGE_DIR}/Source/LibJXR/image/sys
	${FREEIMAGE_DIR}/Source/LibJXR/jxrgluelib
	CACHE PATH "" FORCE)

set(FreeImage_LIBRARIES "" CACHE PATH "" FORCE)

if (WIN32)
	add_definitions(-DFREEIMAGE_LIB -DOPJ_STATIC -DLIBRAW_NODLL)
else()
	add_definitions(-D__ANSI__)
endif()
